CREATE TABLE transactions (transaction_id VARCHAR(255), payer_id VARCHAR(255), transaction_type VARCHAR(255), create_date DATE, transaction_type VARCHAR(255), payment_method VARCHAR(255), amount BIGINT, product_type VARCHAR(255));
CREATE TABLE withdrawals (withdrawal_id VARCHAR(255), account_number VARCHAR(255), create_date DATE, bank_id VARCHAR(255), amount BIGINT, withdraw_user VARCHAR(255));
CREATE TABLE bank_account (bank_account_number VARCHAR(255), account_name VARCHAR(255), merchant_id VARCHAR(255), bank_name VARCHAR(255), bank_address VARCHAR(255), swift_code VARCHAR(255), bank_id VARCHAR(255), settlement_currency VARCHAR(255));
CREATE TABLE account (account_id VARCHAR(255), account_name VARCHAR(255), merchant_id VARCHAR(255), contact_name VARCHAR(255), contact_address VARCHAR(255), contact_phone VARCHAR(255), contact_nationality VARCHAR(255), contact_DOB VARCHAR(255), currency VARCHAR(255));
CREATE TABLE document (document_id VARCHAR(255), document_name VARCHAR(255), document_type VARCHAR(255), merchant_id VARCHAR(255), place_of_issue VARCHAR(255), expiration_date DATE, issue_date DATE, is_account_holder BOOLEAN, is_authorized BOOLEAN);
CREATE TABLE document_images (image_id VARCHAR(255), file_name VARCHAR(255), modify_date DATE, comment VARCHAR(255), document_id VARCHAR(255));
-- CREATE TABLE merchant (merchant_id VARCHAR(255), merchant_name VARCHAR(255), address_street VARCHAR(255), address_city VARCHAR(255), address_province VARCHAR(255), address_country VARCHAR(255), contact_email VARCHAR(255), contact_phone VARCHAR(255), merchant_channel VARCHAR(255), industry VARCHAR(255), trade_country VARCHAR(255), country_of_residence VARCHAR(255), incorporatingCountry VARCHAR(255), trade_country VARCHAR(255), product_type VARCHAR(255), affiliate_id VARCHAR(255), merchant_type VARCHAR(255), expected_transactions VARCHAR(255), expected_revenue VARCHAR(255), account_manager VARCHAR(255), sales_person VARCHAR(255), mcc_code VARCHAR(255), merchant_category VARCHAR(255), risk_level VARCHAR(255), existing_customer_number INT, onboarding_method VARCHAR(255), existing_customer_relationships VARCHAR(255), identity_risk_assessment_completed BOOLEAN, onsite_inspection BOOLEAN, education_export_travel BOOLEAN, trading_start_date DATE, verification_date DATE);
CREATE TABLE payer (payer_id VARCHAR(255), ip_address VARCHAR(255), payer_name VARCHAR(255));
CREATE TABLE user (user_id VARCHAR(255), name VARCHAR(255), email VARCHAR(255), key VARCHAR(255), salt VARCHAR(255), roles_id VARCHAR(255), merchant_id VARCHAR(255));
CREATE TABLE affiliate (affiliate_id VARCHAR(255), name VARCHAR(255), contact_email VARCHAR(255), contact_phone VARCHAR(255), rate_percentage VARCHAR(255), rate_fixed VARCHAR(255), onboarding_date DATE);

CREATE TABLE organisation (merchant_id VARCHAR(255), name VARCHAR(255), address_street VARCHAR(255), address_city VARCHAR(255), address_province VARCHAR(255), contact_email VARCHAR(255), contact_phone VARCHAR(255), organisation_channel VARCHAR(255), country_of_residence VARCHAR(255), industry VARCHAR(255), trade_country VARCHAR(255), product_type VARCHAR(255), affiliate_id VARCHAR(255), organisation_type VARCHAR(255), incorporating_country VARCHAR(255), expected_transactions VARCHAR(255), expected_revenue VARCHAR(255), account_manager VARCHAR(255))